// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zliugbjcnryooxcsrvsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpsaXVnYmpjbnJ5b294Y3NydnNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjc0NTAsImV4cCI6MjA2ODk0MzQ1MH0.kgAE9pxgrM0dcLqBaVi6A-IUD99okvX1Rzgtl5gNLRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});